nilmtk/nilmtk

- nilmtk/dataset_converters/dataport/download_dataport.py
Changed information_schema.tables to information_schema.views to adjust for the restructured Dataport. (TODO) There's only one electricity_egauge_minutes table now, so much of that section is no longer necessary; I didn't adjust for that here.
To increase the speed of the converter, the "get buildings present in this table" and "get first and last timestamps for this house in this table" sections now pull the required information from the metadata table rather than the electricity_egauge_minutes table. This requires much less searching, since the metadata table is much smaller. It should remain accurate since the metadata table is refreshed every time the eGauge tables are refreshed.
> Views Not Tables / Speed Increase

- nilmtk/disaggregate/fhmm_exact.py
> Fhmm multiple homes

- environment.yml
- nilmtk/dataset_converters/greend/metadata/dataset.yaml
Change timezone in Green dataset.yaml to CET to make consistent with the dataset converter.  This prevents some issues when processing multiple timezones (even though they are theoretically the same).
> Fix issue 620

- docs/manual/README.md
- docs/manual/user_guide/install_user.md
Disabled developer installation link in README.md
Added steps for the new installation process in install_user.md
Closes #554, #116, #731, #728
> Updated documentation for the new installation process

- docs/manual/user_guide/install_user.md
added step to include conda-forge channel
> Updated installation process

- nilmtk/metergroup.py
> Please close Issue #313

- docs/manual/user_guide/comparing_nilm_algorithms.ipynb
- docs/manual/user_guide/disaggregation_and_metrics.ipynb
> removed m.label() as it is deprecated

- nilmtk/dataset_converters/eco/convert_eco.py
from_tuple now returns a list
Closes #761
> Changes to ECO dataset_converter

- docs/manual/user_guide/comparing_nilm_algorithms.ipynb
- docs/manual/user_guide/disaggregation_and_metrics.ipynb
Added "if len(v)==0" before squeeze operation
Changes to documentation
Closes #709
> Fixing error on disaggregating over empty dataframes 

- docs/manual/user_guide/run_all_notebooks.md
- docs/manual/user_guide/run_notebooks.py
> Added script to run all notebooks for tests in addition to nosetests.

- nilmtk/dataset_converters/dataport/download_dataport.py
> Added new functions to download_dataport.py

- nilmtk/dataset_converters/__init__.py
- nilmtk/dataset_converters/dred/Readme.md
- nilmtk/dataset_converters/dred/convert_dred.py
- nilmtk/dataset_converters/dred/metadata/building1.yaml
- nilmtk/dataset_converters/dred/metadata/dataset.yaml
- nilmtk/dataset_converters/dred/metadata/meter_devices.yaml
The converter will take the dataset (All_data.csv which is available in the official website)  and will convert to .h5 file. Closes #741
> Added DRED dataset converter taking the actual .csv file

- nilmtk/dataset_converters/dataport/download_dataport.py
changed the script as per latest dataport database. Users can download data in real power, apparent power, phase angle , current and THD.
Data is also available in 1 second intervals.
> modified as per new dataport database

- nilmtk/api.py
@PMeira  I made  the changes in the API which were addressed in the previous pull request by @rajatgupta1234 . There are a few things which will be addressed in future such as proper naming conventions and so on. I also added the doc strings for most of the functions.
> Added the corrected API as requested by Paulo

- nilmtk/dataset_converters/__init__.py
- nilmtk/dataset_converters/smart/convert_smart.py
- nilmtk/dataset_converters/smart/metadata/building1.yaml
- nilmtk/dataset_converters/smart/metadata/building2.yaml
- nilmtk/dataset_converters/smart/metadata/building3.yaml
- nilmtk/dataset_converters/smart/metadata/dataset.yaml
- nilmtk/dataset_converters/smart/metadata/meter_devices.yaml
Currently it works for Homes A, B and C
> Adding  SMART* Dataset converter interface 

- .travis.yml
- ci/build_conda_package.sh
- docs/manual/development_guide/contributing.md
- docs/manual/user_guide/install_user.md
- nilmtk/version.py
- setup.py
> Introduce automated builds (conda packages) on Travis-CI

- nilmtk/api.py
- nilmtk/disaggregate/__init__.py
- nilmtk/disaggregate/combinatorial_optimisation.py
- nilmtk/disaggregate/disaggregator.py
- nilmtk/disaggregate/fhmm_exact.py
- nilmtk/disaggregate/hart_85.py
- nilmtk/disaggregate/mean.py
- nilmtk/losses.py
Changes include
- Changing the API to specify the dissaggregator model directly
- Moved the algorithms Mean, FHMM, CO, Hart to NILMTK
> Moved the baseline algorithms from NILMTK_CONTRIB to NILMTK

- nilmtk/api.py
I added the visualization as a parameter to the dictionary. User can decide if they want to visualize the results or not.
> Added the visualization functionality to the API

- nilmtk/api.py
- Bugfix: https://github.com/nilmtk/nilmtk/issues/890
- Code cleanup by removing unused variables.
> Bugfix RE-API: DROP_ALL_NANS is hardcoded.

- nilmtk/dataset_converters/deddiag/convert_deddiag.py
- nilmtk/dataset_converters/deddiag/metadata/building8.yaml
- nilmtk/dataset_converters/deddiag/metadata/dataset.yaml
- nilmtk/dataset_converters/deddiag/metadata/meter_devices.yaml
- nilmtk/dataset_converters/deddiag/readme.md
This is a converter for a new dataset DEDDIAG ([Scientific Publication](https://doi.org/10.1038/s41597-021-00963-2)  and [Dataset Download](https://doi.org/10.6084/m9.figshare.13615073) ).  
Please see the readme-file to know how to use the converter and how to import data into NILMTK.
> Added DEDDIAG converter

- nilmtk/dataset_converters/__init__.py
- nilmtk/dataset_converters/ideal/convert_ideal.py
I added some __init__.py files to properly install and import the converter. 
Also, I removed some unused lines of code.
Finally, I added in the docstring function a short explanation of what to download to use the converter as I didn't find it explained elsewhere. This may not be the right place to explain this, but it better be somewhere.
> Fixing error in IDEAL dataset converter and addition of some docstrings.

- nilmtk/dataset_converters/dataport/csv_converter.py
This should be used in the case of University-grade access to Pecan Street's data.
Fixes: https://github.com/nilmtk/nilmtk/issues/873
> feat: Add CSV-to-HDF converter for the Dataport free sample.

- nilmtk/metergroup.py
These slight code adjustments aim to enhance Pythonic quality by incorporating python `str.join`
> Code refactoring
